/** Complex JSON Schema keywords retain their native JSON shape in the inspector. */
export const advancedKeywords = [
  [
    "required",
    "Required properties",
    "An array of property names that must be present in this object.",
    "object",
  ],
  [
    "properties",
    "Properties",
    "Schemas for named object properties.",
    "object",
  ],
  [
    "patternProperties",
    "Pattern properties",
    "Map regular expressions to schemas for matching property names.",
    "object",
  ],
  [
    "additionalProperties",
    "Additional properties",
    "Allow extra properties with true, reject them with false, or supply their schema.",
    "object",
  ],
  [
    "propertyNames",
    "Property names",
    "Schema applied to every property name in the object.",
    "object",
  ],
  [
    "dependencies",
    "Dependencies",
    "Property dependencies or schema dependencies, using the document's schema dialect.",
    "object",
  ],
  [
    "dependentRequired",
    "Dependent required",
    "Map a property name to other properties required when it is present.",
    "object",
  ],
  [
    "dependentSchemas",
    "Dependent schemas",
    "Schemas applied when their corresponding property is present.",
    "object",
  ],
  [
    "unevaluatedProperties",
    "Unevaluated properties",
    "Schema or boolean for properties not evaluated by other keywords.",
    "object",
  ],
  [
    "items",
    "Items",
    "Schema for array entries, or tuple schemas in older dialects.",
    "array",
  ],
  [
    "prefixItems",
    "Prefix items",
    "An array of schemas for positional entries in a 2020-12 tuple.",
    "array",
  ],
  [
    "additionalItems",
    "Additional items",
    "Schema or boolean for extra tuple entries in older dialects.",
    "array",
  ],
  [
    "contains",
    "Contains",
    "Schema that at least one array entry must match.",
    "array",
  ],
  [
    "minContains",
    "Minimum matches",
    "Minimum number of entries matching contains (2019-09 and later).",
    "array",
  ],
  [
    "maxContains",
    "Maximum matches",
    "Maximum number of entries matching contains (2019-09 and later).",
    "array",
  ],
  [
    "unevaluatedItems",
    "Unevaluated items",
    "Schema or boolean for array entries not evaluated by other keywords.",
    "array",
  ],
  [
    "allOf",
    "All of",
    "An array of schemas that must all validate the value.",
    "",
  ],
  [
    "anyOf",
    "Any of",
    "An array of schemas; at least one must validate the value.",
    "",
  ],
  [
    "oneOf",
    "One of",
    "An array of schemas; exactly one must validate the value.",
    "",
  ],
  ["not", "Not", "Schema that the value must not satisfy.", ""],
  [
    "if",
    "If",
    "Condition schema selecting the then or else validation branch.",
    "",
  ],
  ["then", "Then", "Schema applied when the if schema matches.", ""],
  ["else", "Else", "Schema applied when the if schema does not match.", ""],
  [
    "$defs",
    "Definitions",
    "Named reusable schemas for 2019-09 and later dialects.",
    "",
  ],
  [
    "definitions",
    "Definitions",
    "Named reusable schemas for draft-07 and earlier dialects.",
    "",
  ],
  [
    "contentEncoding",
    "Content encoding",
    "Encoding of string content, such as base64.",
    "string",
  ],
  [
    "contentMediaType",
    "Content media type",
    "Media type of the string content, such as application/json.",
    "string",
  ],
  [
    "contentSchema",
    "Content schema",
    "Schema describing decoded string content.",
    "string",
  ],
] as const;
export const jsonSchemaFields: Record<string, string> = {
  schemaDefault: "default",
  schemaExamples: "examples",
  schemaConst: "const",
  schemaEnum: "enum",
  ...Object.fromEntries(
    advancedKeywords.map(([keyword]) => [`keyword:${keyword}`, keyword]),
  ),
};
